cc_test(
    name = "snpe_backend_test",
    srcs = ["snpe_backend_test.cc"],
    deps = [
        "//src/backend/snpe:snpe_backend",
        "//src/backend/snpe:snpe_backend_context",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:private"],
)