cc_test(
    name = "pipeline_test",
    srcs = ["pipeline_test.cc"],
    deps = [
        "//src/pipeline:pipeline",
        "//src/pipeline:nodes",
        "//src/utils:types",
        "@googletest//:gtest_main",
    ],
)
