#!/bin/bash
# Platform setup script for Atlas
# Detects platform-specific paths (Android SDK/NDK, SNPE SDK) and writes
# .user.bazelrc so that bazel configurations work out of the box.
#
# Usage:
#   ./tools/platform_setup.sh          # auto-detect and write .user.bazelrc
#   ./tools/platform_setup.sh --quiet  # suppress output, only error on failure
#
# The generated .user.bazelrc is git-ignored and machine-local.
# See .bazelrc for the try-import chain:
#   .bazelrc → try-import .configure.bazelrc → try-import .user.bazelrc

set -e

QUIET=false
if [ "${1:-}" = "--quiet" ]; then
    QUIET=true
fi

log() {
    if ! $QUIET; then
        echo "$@"
    fi
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
USER_BAZELRC="$PROJECT_DIR/.user.bazelrc"

cat > "$USER_BAZELRC" <<EOF
# Auto-generated by tools/platform_setup.sh on $(LC_ALL=C date)
# Platform: $(uname -s) $(uname -m)
# DO NOT EDIT — this file is machine-local and regenerated by platform_setup.sh.
# Add persistent customizations to .bazelrc instead.

EOF

# ---- Android SDK/NDK ----

SDK_CANDIDATES=(
    "$HOME/Library/Android/sdk"
    "/opt/local/usr/android/sdk"
    "/opt/local/usr/android"
)

ANDROID_SDK=""
if [ -n "$ANDROID_HOME" ]; then
    if [ -d "$ANDROID_HOME/platforms" ]; then
        ANDROID_SDK="$ANDROID_HOME"
    elif [ -d "$ANDROID_HOME/sdk/platforms" ]; then
        ANDROID_SDK="$ANDROID_HOME/sdk"
    else
        for candidate in "$ANDROID_HOME/sdk" "$ANDROID_HOME" "${SDK_CANDIDATES[@]}"; do
            if [ -d "$candidate/platforms" ]; then
                ANDROID_SDK="$candidate"
                break
            fi
        done
    fi
else
    for candidate in "${SDK_CANDIDATES[@]}"; do
        if [ -d "$candidate/platforms" ]; then
            ANDROID_SDK="$candidate"
            break
        fi
    done
fi

NDK_CANDIDATES=(
    "$HOME/Library/Android/sdk/ndk"
    "/opt/local/usr/android/ndk"
    "/opt/local/usr/android"
)

_ndk_major_version() {
    local dir="$1"
    local props="$dir/source.properties"
    if [ ! -f "$props" ]; then
        echo 0
        return
    fi
    local rev
    rev=$(grep -E '^Pkg\.Revision[[:space:]]*=' "$props" 2>/dev/null | sed 's/.*=[[:space:]]*//' | sed 's/[.].*//')
    echo "${rev:-0}"
}

_ndk_collect() {
    local -a dirs=()
    if [ -n "$ANDROID_SDK" ] && [ -d "$ANDROID_SDK/ndk" ]; then
        for d in "$ANDROID_SDK/ndk/"*/; do
            [ -d "$d" ] && dirs+=("$d")
        done
    fi
    for candidate in "${NDK_CANDIDATES[@]}"; do
        if [ -d "$candidate" ]; then
            if [ -f "$candidate/source.properties" ] || [ -d "$candidate/toolchains" ]; then
                dirs+=("$candidate")
            else
                for d in "$candidate/"*/; do
                    [ -f "$d/source.properties" ] && dirs+=("$d")
                done
            fi
        fi
    done
    printf '%s\n' "${dirs[@]}" | awk '!seen[$0]++'
}

ANDROID_NDK=""
if [ -n "$ANDROID_NDK_HOME" ] && [ -d "$ANDROID_NDK_HOME" ]; then
    local_ver=$(_ndk_major_version "$ANDROID_NDK_HOME")
    if [ "$local_ver" -ge 27 ] 2>/dev/null; then
        ANDROID_NDK="$ANDROID_NDK_HOME"
    fi
fi

if [ -z "$ANDROID_NDK" ]; then
    best_ndk=""
    best_ver=0
    while IFS= read -r d; do
        [ -z "$d" ] && continue
        d="${d%/}"
        ver=$(_ndk_major_version "$d")
        if [ "$ver" -ge 27 ] 2>/dev/null; then
            if [ "$(uname -s)" = "Darwin" ] && [ "$ver" -eq 28 ]; then
                best_ndk="$d"
                best_ver="$ver"
                break
            fi
            if [ "$ver" -gt "$best_ver" ]; then
                best_ndk="$d"
                best_ver="$ver"
            fi
        fi
    done < <(_ndk_collect)
    ANDROID_NDK="$best_ndk"
fi
if [ -n "$ANDROID_NDK" ]; then
    ANDROID_NDK="${ANDROID_NDK%/}"
fi

if [ -n "$ANDROID_SDK" ]; then
    log "  Android SDK: $ANDROID_SDK"
    cat >> "$USER_BAZELRC" <<EOF
# Android SDK (for android_ndk_repository in WORKSPACE)
build --repo_env=ANDROID_HOME=$ANDROID_SDK
build:android --action_env=ANDROID_HOME=$ANDROID_SDK

EOF
    if [ -n "$ANDROID_NDK" ]; then
        log "  Android NDK: $ANDROID_NDK"
        cat >> "$USER_BAZELRC" <<EOF
# Android NDK (r27+ required by rules_android_ndk, ref WORKSPACE)
build --repo_env=ANDROID_NDK_HOME=$ANDROID_NDK
build:android --action_env=ANDROID_NDK_HOME=$ANDROID_NDK

EOF
    else
        log "  (no Android NDK r27+ found — android_arm64/x86_64 builds will fail)"
    fi
fi

# ---- SNPE SDK (optional backend) ----
# The SNPE repository rule (third_party/snpe/snpe_repo.bzl) reads SNPE_SDK_PATH
# from the environment.  Writing it to .user.bazelrc makes it available as
# --repo_env so that bazel build //... can resolve @snpe_sdk.

SNPE_SDK_PATH="${SNPE_SDK_PATH:-}"
if [ -z "$SNPE_SDK_PATH" ]; then
    SNPE_CANDIDATES=(
        "/opt/qualcomm/snpe"
        "/opt/qcom/snpe"
    )
    for candidate in "${SNPE_CANDIDATES[@]}"; do
        if [ -d "$candidate" ]; then
            SNPE_SDK_PATH="$candidate"
            break
        fi
    done
fi

if [ -n "$SNPE_SDK_PATH" ] && [ -d "$SNPE_SDK_PATH" ]; then
    log "  SNPE SDK:   $SNPE_SDK_PATH"
    cat >> "$USER_BAZELRC" <<EOF
# SNPE SDK (optional backend, used by third_party/snpe/snpe_repo.bzl)
build --repo_env=SNPE_SDK_PATH=$SNPE_SDK_PATH

EOF
else
    log "  (SNPE SDK not found — snpe backend will compile as stub)"
fi

# ---- Platform notes ----
OS="$(uname -s)"
ARCH="$(uname -m)"
if [ "$OS" = "Darwin" ]; then
    if [ "$ARCH" = "arm64" ]; then
        log "  Platform:    macOS arm64 (Apple Silicon)"
        log "  Config:      bazel build //... --config=macos_arm64"
    else
        log "  Platform:    macOS x86_64"
        log "  Config:      bazel build //... --config=macos_x86_64"
    fi
else
    if [ "$ARCH" = "aarch64" ]; then
        log "  Platform:    Linux aarch64"
        log "  Config:      bazel build //... --config=linux_aarch64"
    else
        log "  Platform:    Linux x86_64"
        log "  Config:      bazel build //... --config=linux_x86_64"
    fi
fi

cat >> "$USER_BAZELRC" <<EOF
# End of auto-generated config
EOF

log ""
log "Wrote $USER_BAZELRC"
