cc_test(
    name = "logger_test",
    srcs = ["logger_test.cc"],
    defines = ["ATLAS_ENABLE_LOGGING"],
    deps = [
        "//src/utils:logger",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "strings_test",
    srcs = ["strings_test.cc"],
    deps = [
        "//src/utils:strings",
        "@googletest//:gtest_main",
    ],
)
